services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./prisma/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - HOST=${HOST}
      - PORT=${PORT}
      - ENDPOINT=${ENDPOINT}
      - HTTPS=${HTTPS}
      # - SURVEILLANCE_API_URL=${SURVEILLANCE_API_URL}
      # - SURVEILLANCE_API_CAMERA=${SURVEILLANCE_API_CAMERA}
      # - SURVEILLANCE_API_USERNAME=${SURVEILLANCE_API_USERNAME}
      # - SURVEILLANCE_API_PASSWORD=${SURVEILLANCE_API_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - IMAGE_ENCRYPTION_KEY=${IMAGE_ENCRYPTION_KEY}
      - COOKIE_SECRET=${COOKIE_SECRET}
    depends_on:
      - db
    volumes:
      - ./frontend/public:/app/public # Para desenvolvimento local com npm do front rodando diretamente no host
      # - system-images:/app/public
      - visitor-images:/app/uploads
      - ./backend/prisma/migrations:/app/prisma/migrations
    # command: ["sh", "-c", "npx prisma migrate deploy && yarn start"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: frontend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED}
      - HTTPS=${FRONTEND_HTTPS}
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db:
  visitor-images:
  prometheus_data:
  grafana_data:
